---
- name: dbserver setup
  hosts: dbservers
  become: yes
    #vars:
    #dbname: electric
    #dbuser: current
    #dbpass: tesla
  tasks:
    - debug:
        msg: "The dbname is {{dbname}}"

    - debug:
        var: dbuser

    - name: Install MariaDb-server
      ansible.builtin.yum:
        name: mariadb-server
        state: present
    - name: Start MariaDb-server
      ansible.builtin.service:
        name: mariadb
        state: started
    - name: Install python3-PyMySql
      ansible.builtin.yum:
        name: python3-PyMySQL
        state: present
    - name: To Create database 
      community.mysql.mysql_db:
        name: "{{dbname}}"
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock
    - name: Create database user 
      community.mysql.mysql_user:
        name: "{{dbuser}}"
        password: "{{dbpass}}"
        priv: '*.*:ALL'
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock
      register: dbout
    - name: print dbout data
      debug:
        var: dbout
