apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: redis
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: user-secret
            key: username
            optional: False
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: user-secret
            key: password
            optional: False
