---
- name: dbserver setup
  hosts: dbservers
  become: yes
  tasks:
    - name: Install MariaDb-server
      ansible.builtin.yum:
        name: mariadb-server
        state: present
    - name: Start MariaDb-server
      ansible.builtin.service:
        name: mariadb
        state: started
    - name: Install python3-PyMySql
      ansible.builtin.yum:
        name: python3-PyMySQL
        state: present
    - name: To Create database name 'accounts'
      community.mysql.mysql_db:
        name: accounts
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock
    - name: Create database user with name  'vprofile'
      community.mysql.mysql_user:
        name: vprofile
        password: 'harish1277'
        priv: '*.*:ALL'
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock
